version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
     - "3000:8080"
    volumes:
      - ./:/go/src/app
    tty: true
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    hostname: postgres
    ports:
      - "5432:5432"
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    hostname: pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always
volumes:
  data: